<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Poolaris.NodeGui</AssemblyName>
    <RootNamespace>Poolaris.NodeGui</RootNamespace>
    <ApplicationIcon>Assets\poolaris.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
